
```{r}
casos=readRDS("casos.rds")
visual=aggregate(data=casos, metodo~depa + sexo + semana, length)

visual=visual[visual$sexo%in%c("FEMENINO", "MASCULINO"),]
```

```{r, results='asis'}
library(ggplot2)
library(plotly)

plot_ly(visual, alpha  = 0.5) %>%
  add_bars(
    x = ~depa, y = ~abs(metodo),
    frame = ~semana, 
    color = ~factor(sexo),
    line = list(simplify = FALSE)
  ) %>%
  layout(yaxis = list(title = "US population"))
```
```{r}

gg <- ggplot(visual, aes(semana, metodo, color = sexo)) +
  geom_line(aes(frame = semana, ids = depa),group=1) +
  scale_y_log10() + facet_grid(~sexo)
ggplotly(gg) %>%
  animation_opts(frame = 100,transition = 0,
                 easing = "linear",
                 redraw = F)
```
```{r}

library(plotly)

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}
fig=visual
# df <- txhousing 
# fig <- df %>%
#   filter(year > 2005, city %in% c("Abilene", "Bay Area"))
fig <- fig %>% accumulate_by(~semana)


fig <- fig %>%
  plot_ly(
    x = ~semana, 
    y = ~metodo,
    split = ~sexo,
    #frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F)
  )
fig <- fig %>% layout(
  xaxis = list(
    title = "Date",
    zeroline = F
  ),
  yaxis = list(
    title = "Median",
    zeroline = F
  )
) 
fig <- fig %>% animation_opts(
  frame = 100, 
  transition = 0, 
  redraw = FALSE
)
fig <- fig %>% animation_slider(
  hide = T
)
fig <- fig %>% animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)

fig
```

